AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/main.rb' 

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
