AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/main.rb' 

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Exclude:
    - 'lib/main.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false